import React from "react";
import { FileText, Download, CheckCircle2, AlertTriangle } from "lucide-react";
import { motion } from "framer-motion";

interface DiscoveryBriefProps {
  target: any;
  results: any[];
}

export default function DiscoveryBrief({ target, results }: DiscoveryBriefProps) {
  if (!target || !results || results.length === 0) return null;

  const topHit = results[0];
  const isGoodCandidate = topHit.affinityScore <= -8.0 && topHit.toxicityRisk === "Low" && topHit.lipinskiPass;

  const handleDownload = () => {
    const reportText = `
NovaScreen Discovery Brief
===========================
Target: ${target.name} (${target.pdbId})
Description: ${target.description}

Top Candidate: ${topHit.compound.name} (${topHit.compound.formula})
Affinity Score: ${topHit.affinityScore} kcal/mol
Toxicity Risk: ${topHit.toxicityRisk}
Lipinski Pass: ${topHit.lipinskiPass ? "Yes" : "No"}

Notes: ${topHit.notes}

Generated by NovaScreen Serverless AI Edge.
    `.trim();

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NovaScreen_Brief_${target.pdbId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-panel p-6 mt-6 border border-brand-teal/30 relative overflow-hidden"
    >
      <div className="absolute top-0 right-0 w-64 h-64 bg-brand-teal/5 blur-[80px] pointer-events-none rounded-full" />
      
      <div className="flex items-start justify-between mb-6">
        <div>
          <h3 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <FileText className="w-5 h-5 text-brand-teal" />
            Executive Discovery Brief
          </h3>
          <p className="text-sm text-slate-400 mt-1">Generated by Serverless Pipeline</p>
        </div>
        <button 
          onClick={handleDownload}
          className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-brand-teal text-sm font-medium rounded-md transition-colors border border-brand-teal/20"
        >
          <Download className="w-4 h-4" />
          Export TXT
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 relative z-10">
        <div className="space-y-4">
          <div>
            <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Primary Target Analysis</h4>
            <div className="bg-slate-900/50 rounded-lg p-3 border border-slate-800">
              <div className="text-sm text-slate-300"><span className="text-slate-500">Protein:</span> {target.name}</div>
              <div className="text-sm text-slate-300"><span className="text-slate-500">PDB ID:</span> {target.pdbId}</div>
              <div className="text-sm text-slate-300 mt-2 line-clamp-2">{target.description}</div>
            </div>
          </div>

          <div>
            <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">Lead Compound (Hit #1)</h4>
            <div className="bg-slate-900/50 rounded-lg p-3 border border-slate-800">
              <div className="text-lg font-bold text-brand-teal mb-1">{topHit.compound.name}</div>
              <div className="text-xs text-slate-400 font-mono mb-3">{topHit.compound.smiles}</div>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div>
                  <span className="text-slate-500 block text-[10px] uppercase">Binding Energy</span>
                  <span className="text-slate-200 font-semibold">{topHit.affinityScore} <span className="text-slate-500 text-xs font-normal">kcal/mol</span></span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px] uppercase">Safety Profile</span>
                  <span className={topHit.toxicityRisk === "Low" ? "text-emerald-400 font-semibold" : "text-amber-400 font-semibold"}>
                    {topHit.toxicityRisk} Risk
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div>
          <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">AI Pipeline Conclusion</h4>
          <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-800 h-[calc(100%-1.5rem)] flex flex-col">
            {isGoodCandidate ? (
              <div className="flex gap-3 mb-4 text-emerald-400">
                <CheckCircle2 className="w-5 h-5 shrink-0" />
                <p className="text-sm font-medium">Viable candidate identified for progression.</p>
              </div>
            ) : (
              <div className="flex gap-3 mb-4 text-amber-400">
                <AlertTriangle className="w-5 h-5 shrink-0" />
                <p className="text-sm font-medium">Sub-optimal profiles detected. Lead optimization required.</p>
              </div>
            )}
            
            <p className="text-sm text-slate-400 leading-relaxed flex-1">
              Virtual screening across the compound library identified <strong className="text-slate-200">{topHit.compound.name}</strong> as the top binder. 
              {topHit.lipinskiPass 
                ? " The molecule exhibits favorable drug-like properties according to Lipinski's Rule of Five." 
                : " However, it violates one or more drug-like properties."} 
              <br/><br/>
              <strong>Recommendation:</strong> {isGoodCandidate ? "Proceed to in-vitro validation assays and cellular testing." : "Initiate analog synthesis to improve binding affinity and toxicity profile."}
            </p>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
